//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyComuter1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmissionLog
    {
        public int id { get; set; }
        public string ssn { get; set; }
        public string vType { get; set; }
        public Nullable<decimal> distance { get; set; }
        public Nullable<decimal> co2 { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
